// Generated by scripts/hve-squad-release.mjs from the latest stable Peter-N91/hve-squad release. Do not edit.
export const hveSquadRelease = {
  "version": "0.18.1",
  "tag": "v0.18.1",
  "url": "https://github.com/Peter-N91/hve-squad/releases/tag/v0.18.1",
  "publishedAt": "2026-10-07T18:03:09Z"
} as const
